/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SumInterface extends Interface {
  getFunction(
    nameOrSignature: "add" | "firstNoSet" | "secondNoSet"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "add", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "firstNoSet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "secondNoSet",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "firstNoSet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "secondNoSet",
    data: BytesLike
  ): Result;
}

export interface Sum extends BaseContract {
  connect(runner?: ContractRunner | null): Sum;
  waitForDeployment(): Promise<this>;

  interface: SumInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[], [bigint], "view">;

  firstNoSet: TypedContractMethod<[x: BigNumberish], [void], "nonpayable">;

  secondNoSet: TypedContractMethod<[y: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "firstNoSet"
  ): TypedContractMethod<[x: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "secondNoSet"
  ): TypedContractMethod<[y: BigNumberish], [void], "nonpayable">;

  filters: {};
}
